<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SugestaoPonto;
use Illuminate\Support\Facades\DB;


class TodosPontosAcupunturaSeeder extends Seeder
{
    public function run()
    {
        $pontos = [
            // Pontos do Pulmão (P) - 11 pontos
            ['ponto' => 'P1', 'descricao' => 'Pulmão 1 - Alivia tosse e problemas respiratórios.'],
            ['ponto' => 'P2', 'descricao' => 'Pulmão 2 - Beneficia os pulmões e alivia dor no peito.'],
            ['ponto' => 'P3', 'descricao' => 'Pulmão 3 - Alivia tosse e problemas respiratórios.'],
            ['ponto' => 'P4', 'descricao' => 'Pulmão 4 - Beneficia os pulmões e acalma a tosse.'],
            ['ponto' => 'P5', 'descricao' => 'Pulmão 5 - Alivia febre e distúrbios pulmonares.'],
            ['ponto' => 'P6', 'descricao' => 'Pulmão 6 - Trata dor no braço e pulmões.'],
            ['ponto' => 'P7', 'descricao' => 'Pulmão 7 - Alivia resfriados e tosse seca.'],
            ['ponto' => 'P8', 'descricao' => 'Pulmão 8 - Beneficia a garganta e pulmões.'],
            ['ponto' => 'P9', 'descricao' => 'Pulmão 9 - Tonifica o Qi e regula os pulmões.'],
            ['ponto' => 'P10', 'descricao' => 'Pulmão 10 - Alivia a garganta e febres.'],
            ['ponto' => 'P11', 'descricao' => 'Pulmão 11 - Alivia dor de garganta e febre alta.'],

            // Pontos do Intestino Grosso (IG) - 20 pontos
            ['ponto' => 'IG1', 'descricao' => 'Intestino Grosso 1 - Alivia dor de dente e garganta.'],
            ['ponto' => 'IG2', 'descricao' => 'Intestino Grosso 2 - Alivia febre e constipação.'],
            ['ponto' => 'IG3', 'descricao' => 'Intestino Grosso 3 - Alivia dor de dente e febre.'],
            ['ponto' => 'IG4', 'descricao' => 'Intestino Grosso 4 - Alivia dor e congestão nasal.'],
            ['ponto' => 'IG5', 'descricao' => 'Intestino Grosso 5 - Beneficia os olhos e garganta.'],
            ['ponto' => 'IG6', 'descricao' => 'Intestino Grosso 6 - Alivia dor nos braços e mãos.'],
            ['ponto' => 'IG7', 'descricao' => 'Intestino Grosso 7 - Alivia dor de cabeça e febre.'],
            ['ponto' => 'IG8', 'descricao' => 'Intestino Grosso 8 - Alivia dor no ombro e braço.'],
            ['ponto' => 'IG9', 'descricao' => 'Intestino Grosso 9 - Beneficia o braço e ombro.'],
            ['ponto' => 'IG10', 'descricao' => 'Intestino Grosso 10 - Alivia dor e rigidez muscular.'],
            ['ponto' => 'IG11', 'descricao' => 'Intestino Grosso 11 - Alivia febre e congestão.'],
            ['ponto' => 'IG12', 'descricao' => 'Intestino Grosso 12 - Alivia dor no ombro.'],
            ['ponto' => 'IG13', 'descricao' => 'Intestino Grosso 13 - Alivia dor nos ombros e braços.'],
            ['ponto' => 'IG14', 'descricao' => 'Intestino Grosso 14 - Beneficia os olhos e ombro.'],
            ['ponto' => 'IG15', 'descricao' => 'Intestino Grosso 15 - Alivia dor e rigidez no ombro.'],
            ['ponto' => 'IG16', 'descricao' => 'Intestino Grosso 16 - Beneficia o ombro e pescoço.'],
            ['ponto' => 'IG17', 'descricao' => 'Intestino Grosso 17 - Alivia dor de garganta e tosse.'],
            ['ponto' => 'IG18', 'descricao' => 'Intestino Grosso 18 - Alivia dor de dente e garganta.'],
            ['ponto' => 'IG19', 'descricao' => 'Intestino Grosso 19 - Beneficia o nariz e ouvidos.'],
            ['ponto' => 'IG20', 'descricao' => 'Intestino Grosso 20 - Beneficia o nariz e alivia congestão.'],

            // Pontos do Estômago (E) - 45 pontos
            ['ponto' => 'E1', 'descricao' => 'Estômago 1 - Alivia problemas oculares e dor de cabeça.'],
            ['ponto' => 'E2', 'descricao' => 'Estômago 2 - Alivia dor facial e problemas dentários.'],
            ['ponto' => 'E3', 'descricao' => 'Estômago 3 - Alivia dor facial e problemas nas gengivas.'],
            ['ponto' => 'E4', 'descricao' => 'Estômago 4 - Alivia dor na mandíbula e problemas dentários.'],
            ['ponto' => 'E5', 'descricao' => 'Estômago 5 - Alivia dor facial e problemas dentários.'],
            ['ponto' => 'E6', 'descricao' => 'Estômago 6 - Alivia dor facial e problemas na mandíbula.'],
            ['ponto' => 'E7', 'descricao' => 'Estômago 7 - Alivia dor facial e problemas dentários.'],
            ['ponto' => 'E8', 'descricao' => 'Estômago 8 - Alivia dor facial e problemas oculares.'],
            ['ponto' => 'E9', 'descricao' => 'Estômago 9 - Alivia dor facial e problemas de garganta.'],
            ['ponto' => 'E10', 'descricao' => 'Estômago 10 - Alivia dor facial e problemas digestivos.'],
            ['ponto' => 'E11', 'descricao' => 'Estômago 11 - Alivia dor abdominal e distúrbios digestivos.'],
            ['ponto' => 'E12', 'descricao' => 'Estômago 12 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E13', 'descricao' => 'Estômago 13 - Alivia dor abdominal e distúrbios respiratórios.'],
            ['ponto' => 'E14', 'descricao' => 'Estômago 14 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E15', 'descricao' => 'Estômago 15 - Alivia dor abdominal e problemas respiratórios.'],
            ['ponto' => 'E16', 'descricao' => 'Estômago 16 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E17', 'descricao' => 'Estômago 17 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E18', 'descricao' => 'Estômago 18 - Alivia dor abdominal e distúrbios respiratórios.'],
            ['ponto' => 'E19', 'descricao' => 'Estômago 19 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E20', 'descricao' => 'Estômago 20 - Alivia dor abdominal e problemas respiratórios.'],
            ['ponto' => 'E21', 'descricao' => 'Estômago 21 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E22', 'descricao' => 'Estômago 22 - Alivia dor abdominal e distúrbios digestivos.'],
            ['ponto' => 'E23', 'descricao' => 'Estômago 23 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E24', 'descricao' => 'Estômago 24 - Alivia dor abdominal e distúrbios digestivos.'],
            ['ponto' => 'E25', 'descricao' => 'Estômago 25 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E26', 'descricao' => 'Estômago 26 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E27', 'descricao' => 'Estômago 27 - Alivia dor abdominal e distúrbios digestivos.'],
            ['ponto' => 'E28', 'descricao' => 'Estômago 28 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E29', 'descricao' => 'Estômago 29 - Alivia dor abdominal e problemas urinários.'],
            ['ponto' => 'E30', 'descricao' => 'Estômago 30 - Alivia dor abdominal e problemas menstruais.'],
            ['ponto' => 'E31', 'descricao' => 'Estômago 31 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'E32', 'descricao' => 'Estômago 32 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E33', 'descricao' => 'Estômago 33 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'E34', 'descricao' => 'Estômago 34 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E35', 'descricao' => 'Estômago 35 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'E36', 'descricao' => 'Estômago 36 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E37', 'descricao' => 'Estômago 37 - Alivia dor abdominal e distúrbios digestivos.'],
            ['ponto' => 'E38', 'descricao' => 'Estômago 38 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E39', 'descricao' => 'Estômago 39 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E40', 'descricao' => 'Estômago 40 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E41', 'descricao' => 'Estômago 41 - Alivia dor abdominal e distúrbios digestivos.'],
            ['ponto' => 'E42', 'descricao' => 'Estômago 42 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E43', 'descricao' => 'Estômago 43 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'E44', 'descricao' => 'Estômago 44 - Alivia dor abdominal e distúrbios digestivos.'],
            ['ponto' => 'E45', 'descricao' => 'Estômago 45 - Alivia dor abdominal e problemas digestivos.'],


            // Pontos do Baço-Pâncreas (BP) - 21 pontos
            ['ponto' => 'BP1', 'descricao' => 'Baço-Pâncreas 1 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'BP2', 'descricao' => 'Baço-Pâncreas 2 - Alivia distúrbios digestivos e febre.'],
            ['ponto' => 'BP3', 'descricao' => 'Baço-Pâncreas 3 - Tonifica o Baço e regula o Qi.'],
            ['ponto' => 'BP4', 'descricao' => 'Baço-Pâncreas 4 - Alivia dor abdominal e vômitos.'],
            ['ponto' => 'BP5', 'descricao' => 'Baço-Pâncreas 5 - Beneficia o Baço e regula a digestão.'],
            ['ponto' => 'BP6', 'descricao' => 'Baço-Pâncreas 6 - Regula o fígado, Baço e rins.'],
            ['ponto' => 'BP7', 'descricao' => 'Baço-Pâncreas 7 - Alivia inchaço e dor abdominal.'],
            ['ponto' => 'BP8', 'descricao' => 'Baço-Pâncreas 8 - Beneficia a menstruação e dor abdominal.'],
            ['ponto' => 'BP9', 'descricao' => 'Baço-Pâncreas 9 - Alivia edema e retensão de líquidos.'],
            ['ponto' => 'BP10', 'descricao' => 'Baço-Pâncreas 10 - Alivia problemas de pele e regula o sangue.'],
            ['ponto' => 'BP11', 'descricao' => 'Baço-Pâncreas 11 - Alivia dor nas pernas e joelhos.'],
            ['ponto' => 'BP12', 'descricao' => 'Baço-Pâncreas 12 - Beneficia a bexiga e órgãos genitais.'],
            ['ponto' => 'BP13', 'descricao' => 'Baço-Pâncreas 13 - Beneficia o abdômen inferior.'],
            ['ponto' => 'BP14', 'descricao' => 'Baço-Pâncreas 14 - Alivia dor na parte superior do abdômen.'],
            ['ponto' => 'BP15', 'descricao' => 'Baço-Pâncreas 15 - Regula o intestino e beneficia o Baço.'],
            ['ponto' => 'BP16', 'descricao' => 'Baço-Pâncreas 16 - Regula a digestão.'],
            ['ponto' => 'BP17', 'descricao' => 'Baço-Pâncreas 17 - Alivia dor no abdômen e peito.'],
            ['ponto' => 'BP18', 'descricao' => 'Baço-Pâncreas 18 - Alivia dor e distensão no abdômen.'],
            ['ponto' => 'BP19', 'descricao' => 'Baço-Pâncreas 19 - Beneficia o estômago e regula Qi.'],
            ['ponto' => 'BP20', 'descricao' => 'Baço-Pâncreas 20 - Tonifica o Baço e regula o estômago.'],
            ['ponto' => 'BP21', 'descricao' => 'Baço-Pâncreas 21 - Alivia dor em todo o corpo.'],

            // Triplo Aquecedor (TA) - 23 pontos
            ['ponto' => 'TA1', 'descricao' => 'Triplo Aquecedor 1 - Alivia dor de garganta e ouvidos.'],
            ['ponto' => 'TA2', 'descricao' => 'Triplo Aquecedor 2 - Alivia dor nos dedos e mãos.'],
            ['ponto' => 'TA3', 'descricao' => 'Triplo Aquecedor 3 - Beneficia os ouvidos e cabeça.'],
            ['ponto' => 'TA4', 'descricao' => 'Triplo Aquecedor 4 - Tonifica Qi e regula o Triplo Aquecedor.'],
            ['ponto' => 'TA5', 'descricao' => 'Triplo Aquecedor 5 - Alivia febre e dores de cabeça.'],
            ['ponto' => 'TA6', 'descricao' => 'Triplo Aquecedor 6 - Alivia constipação e dor abdominal.'],
            ['ponto' => 'TA7', 'descricao' => 'Triplo Aquecedor 7 - Alivia dor e inchaço nos ouvidos.'],
            ['ponto' => 'TA8', 'descricao' => 'Triplo Aquecedor 8 - Beneficia os ombros e braços.'],
            ['ponto' => 'TA9', 'descricao' => 'Triplo Aquecedor 9 - Alivia dor nos ombros e costas.'],
            ['ponto' => 'TA10', 'descricao' => 'Triplo Aquecedor 10 - Alivia inchaço e dor nas articulações.'],
            ['ponto' => 'TA11', 'descricao' => 'Triplo Aquecedor 11 - Alivia dor nos ombros e cotovelo.'],
            ['ponto' => 'TA12', 'descricao' => 'Triplo Aquecedor 12 - Beneficia o ombro e dor nas costas.'],
            ['ponto' => 'TA13', 'descricao' => 'Triplo Aquecedor 13 - Alivia dor no braço e cotovelo.'],
            ['ponto' => 'TA14', 'descricao' => 'Triplo Aquecedor 14 - Alivia dor no ombro.'],
            ['ponto' => 'TA15', 'descricao' => 'Triplo Aquecedor 15 - Alivia dor nas costas e pescoço.'],
            ['ponto' => 'TA16', 'descricao' => 'Triplo Aquecedor 16 - Beneficia a garganta e dor de ouvido.'],
            ['ponto' => 'TA17', 'descricao' => 'Triplo Aquecedor 17 - Beneficia os ouvidos e garganta.'],
            ['ponto' => 'TA18', 'descricao' => 'Triplo Aquecedor 18 - Alivia dor de ouvido e cabeça.'],
            ['ponto' => 'TA19', 'descricao' => 'Triplo Aquecedor 19 - Beneficia os ouvidos e alivia zumbido.'],
            ['ponto' => 'TA20', 'descricao' => 'Triplo Aquecedor 20 - Alivia dor de ouvido e mandíbula.'],
            ['ponto' => 'TA21', 'descricao' => 'Triplo Aquecedor 21 - Beneficia os ouvidos e alivia a dor de dente.'],
            ['ponto' => 'TA22', 'descricao' => 'Triplo Aquecedor 22 - Beneficia os ouvidos e alivia a dor facial.'],
            ['ponto' => 'TA23', 'descricao' => 'Triplo Aquecedor 23 - Beneficia os olhos e alivia dor de cabeça.'],

            // Vesícula Biliar (VB) - 44 pontos
            ['ponto' => 'VB1', 'descricao' => 'Vesícula Biliar 1 - Alivia dor de cabeça e problemas oculares.'],
            ['ponto' => 'VB2', 'descricao' => 'Vesícula Biliar 2 - Alivia dor de ouvido e mandíbula.'],
            ['ponto' => 'VB3', 'descricao' => 'Vesícula Biliar 3 - Alivia dor de cabeça e pressão ocular.'],
            ['ponto' => 'VB4', 'descricao' => 'Vesícula Biliar 4 - Alivia dor de cabeça e dor nos olhos.'],
            ['ponto' => 'VB5', 'descricao' => 'Vesícula Biliar 5 - Alivia enxaqueca e dor temporal.'],
            ['ponto' => 'VB6', 'descricao' => 'Vesícula Biliar 6 - Alivia dor de cabeça e congestão nasal.'],
            ['ponto' => 'VB7', 'descricao' => 'Vesícula Biliar 7 - Alivia dor de cabeça e zumbido nos ouvidos.'],
            ['ponto' => 'VB8', 'descricao' => 'Vesícula Biliar 8 - Alivia dor de cabeça e tontura.'],
            ['ponto' => 'VB9', 'descricao' => 'Vesícula Biliar 9 - Alivia dor de cabeça e problemas oculares.'],
            ['ponto' => 'VB10', 'descricao' => 'Vesícula Biliar 10 - Alivia rigidez no pescoço e dor de cabeça.'],
            ['ponto' => 'VB11', 'descricao' => 'Vesícula Biliar 11 - Alivia dor no ombro e dor torácica.'],
            ['ponto' => 'VB12', 'descricao' => 'Vesícula Biliar 12 - Alivia dor nas costas e rigidez no pescoço.'],
            ['ponto' => 'VB13', 'descricao' => 'Vesícula Biliar 13 - Alivia problemas digestivos e ansiedade.'],
            ['ponto' => 'VB14', 'descricao' => 'Vesícula Biliar 14 - Alivia dor na cabeça e tensão facial.'],
            ['ponto' => 'VB15', 'descricao' => 'Vesícula Biliar 15 - Alivia dor de cabeça e pressão no peito.'],
            ['ponto' => 'VB16', 'descricao' => 'Vesícula Biliar 16 - Alivia tontura e dor de cabeça.'],
            ['ponto' => 'VB17', 'descricao' => 'Vesícula Biliar 17 - Alivia dor nos ombros e pescoço.'],
            ['ponto' => 'VB18', 'descricao' => 'Vesícula Biliar 18 - Alivia dor nas costas e costelas.'],
            ['ponto' => 'VB19', 'descricao' => 'Vesícula Biliar 19 - Alivia dor nos ombros e nas costas.'],
            ['ponto' => 'VB20', 'descricao' => 'Vesícula Biliar 20 - Alivia dor de cabeça, enxaqueca e rigidez no pescoço.'],
            ['ponto' => 'VB21', 'descricao' => 'Vesícula Biliar 21 - Alivia dor nos ombros e tensão muscular.'],
            ['ponto' => 'VB22', 'descricao' => 'Vesícula Biliar 22 - Alivia dor no peito e ombros.'],
            ['ponto' => 'VB23', 'descricao' => 'Vesícula Biliar 23 - Alivia dor no peito e desconforto abdominal.'],
            ['ponto' => 'VB24', 'descricao' => 'Vesícula Biliar 24 - Alivia problemas digestivos e dor no peito.'],
            ['ponto' => 'VB25', 'descricao' => 'Vesícula Biliar 25 - Alivia dor nas costas e problemas digestivos.'],
            ['ponto' => 'VB26', 'descricao' => 'Vesícula Biliar 26 - Alivia dor abdominal e distensão.'],
            ['ponto' => 'VB27', 'descricao' => 'Vesícula Biliar 27 - Alivia dor abdominal e problemas urinários.'],
            ['ponto' => 'VB28', 'descricao' => 'Vesícula Biliar 28 - Alivia dor abdominal e distúrbios genitais.'],
            ['ponto' => 'VB29', 'descricao' => 'Vesícula Biliar 29 - Alivia dor na parte inferior das costas e quadris.'],
            ['ponto' => 'VB30', 'descricao' => 'Vesícula Biliar 30 - Alivia dor no quadril e ciática.'],
            ['ponto' => 'VB31', 'descricao' => 'Vesícula Biliar 31 - Alivia dor nas pernas e joelhos.'],
            ['ponto' => 'VB32', 'descricao' => 'Vesícula Biliar 32 - Alivia fraqueza nas pernas e dor nas articulações.'],
            ['ponto' => 'VB33', 'descricao' => 'Vesícula Biliar 33 - Alivia dor nas coxas e pernas.'],
            ['ponto' => 'VB34', 'descricao' => 'Vesícula Biliar 34 - Beneficia os tendões e alivia dor nas articulações.'],
            ['ponto' => 'VB35', 'descricao' => 'Vesícula Biliar 35 - Alivia dor nas pernas e pés.'],
            ['ponto' => 'VB36', 'descricao' => 'Vesícula Biliar 36 - Alivia dor nas pernas e câimbras.'],
            ['ponto' => 'VB37', 'descricao' => 'Vesícula Biliar 37 - Alivia dor nos olhos e problemas visuais.'],
            ['ponto' => 'VB38', 'descricao' => 'Vesícula Biliar 38 - Alivia dor nas pernas e tornozelo.'],
            ['ponto' => 'VB39', 'descricao' => 'Vesícula Biliar 39 - Alivia rigidez no pescoço e dor nas pernas.'],
            ['ponto' => 'VB40', 'descricao' => 'Vesícula Biliar 40 - Alivia dor nas articulações e tornozelo.'],
            ['ponto' => 'VB41', 'descricao' => 'Vesícula Biliar 41 - Beneficia os olhos e alivia dor de cabeça.'],
            ['ponto' => 'VB42', 'descricao' => 'Vesícula Biliar 42 - Alivia dor nos pés e tornozelos.'],
            ['ponto' => 'VB43', 'descricao' => 'Vesícula Biliar 43 - Alivia dor nos pés e dor de cabeça.'],
            ['ponto' => 'VB44', 'descricao' => 'Vesícula Biliar 44 - Alivia dor nos pés e problemas oculares.'],


            // Fígado (F) - 14 pontos

            ['ponto' => 'F1', 'descricao' => 'Fígado 1 - Alivia dor abdominal, problemas menstruais e distúrbios urinários.'],
            ['ponto' => 'F2', 'descricao' => 'Fígado 2 - Alivia dor de cabeça, zumbido nos ouvidos, irritabilidade e problemas menstruais.'],
            ['ponto' => 'F3', 'descricao' => 'Fígado 3 - Alivia dor de cabeça, problemas oculares, hipertensão e regula a menstruação.'],
            ['ponto' => 'F4', 'descricao' => 'Fígado 4 - Alivia dor nos pés, problemas menstruais e distúrbios urinários.'],
            ['ponto' => 'F5', 'descricao' => 'Fígado 5 - Alivia problemas menstruais, distúrbios urinários e dor abdominal.'],
            ['ponto' => 'F6', 'descricao' => 'Fígado 6 - Alivia dor abdominal, distúrbios menstruais e problemas urinários.'],
            ['ponto' => 'F7', 'descricao' => 'Fígado 7 - Alivia dor nas pernas, distensão abdominal e problemas menstruais.'],
            ['ponto' => 'F8', 'descricao' => 'Fígado 8 - Alivia dor no joelho, dor nas costas e distúrbios menstruais.'],
            ['ponto' => 'F9', 'descricao' => 'Fígado 9 - Alivia dor abdominal, dor nas pernas e distúrbios menstruais.'],
            ['ponto' => 'F10', 'descricao' => 'Fígado 10 - Alivia dor abdominal, dor nas pernas e distúrbios genitais.'],
            ['ponto' => 'F11', 'descricao' => 'Fígado 11 - Alivia dor abdominal, problemas urinários e distúrbios menstruais.'],
            ['ponto' => 'F12', 'descricao' => 'Fígado 12 - Alivia dor abdominal, problemas urinários e distúrbios menstruais.'],
            ['ponto' => 'F13', 'descricao' => 'Fígado 13 - Alivia dor abdominal, problemas digestivos e distúrbios menstruais.'],
            ['ponto' => 'F14', 'descricao' => 'Fígado 14 - Alivia dor torácica, problemas digestivos e distúrbios menstruais.'],

            // Vaso Concepção (VC) - 24 pontos

            ['ponto' => 'VC1', 'descricao' => 'Vaso Concepção 1 - Alivia dor abdominal e problemas menstruais.'],
            ['ponto' => 'VC2', 'descricao' => 'Vaso Concepção 2 - Alivia problemas urinários e distúrbios menstruais.'],
            ['ponto' => 'VC3', 'descricao' => 'Vaso Concepção 3 - Alivia dor abdominal e regula a menstruação.'],
            ['ponto' => 'VC4', 'descricao' => 'Vaso Concepção 4 - Alivia dor abdominal, problemas menstruais e problemas digestivos.'],
            ['ponto' => 'VC5', 'descricao' => 'Vaso Concepção 5 - Alivia dor abdominal e regula a menstruação.'],
            ['ponto' => 'VC6', 'descricao' => 'Vaso Concepção 6 - Alivia dor abdominal e problemas menstruais, melhora a digestão.'],
            ['ponto' => 'VC7', 'descricao' => 'Vaso Concepção 7 - Alivia dor abdominal e problemas urinários.'],
            ['ponto' => 'VC8', 'descricao' => 'Vaso Concepção 8 - Alivia problemas menstruais e dor abdominal.'],
            ['ponto' => 'VC9', 'descricao' => 'Vaso Concepção 9 - Alivia problemas digestivos e dor abdominal.'],
            ['ponto' => 'VC10', 'descricao' => 'Vaso Concepção 10 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'VC11', 'descricao' => 'Vaso Concepção 11 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'VC12', 'descricao' => 'Vaso Concepção 12 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'VC13', 'descricao' => 'Vaso Concepção 13 - Alivia problemas digestivos e dor abdominal.'],
            ['ponto' => 'VC14', 'descricao' => 'Vaso Concepção 14 - Alivia dor abdominal e problemas digestivos.'],
            ['ponto' => 'VC15', 'descricao' => 'Vaso Concepção 15 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'VC16', 'descricao' => 'Vaso Concepção 16 - Alivia problemas digestivos e dor abdominal.'],
            ['ponto' => 'VC17', 'descricao' => 'Vaso Concepção 17 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'VC18', 'descricao' => 'Vaso Concepção 18 - Alivia problemas digestivos e dor abdominal.'],
            ['ponto' => 'VC19', 'descricao' => 'Vaso Concepção 19 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'VC20', 'descricao' => 'Vaso Concepção 20 - Alivia problemas digestivos e dor abdominal.'],
            ['ponto' => 'VC21', 'descricao' => 'Vaso Concepção 21 - Alivia dor abdominal e problemas menstruais.'],
            ['ponto' => 'VC22', 'descricao' => 'Vaso Concepção 22 - Alivia problemas digestivos e dor abdominal.'],
            ['ponto' => 'VC23', 'descricao' => 'Vaso Concepção 23 - Alivia dor abdominal e distúrbios menstruais.'],
            ['ponto' => 'VC24', 'descricao' => 'Vaso Concepção 24 - Alivia dor abdominal e problemas digestivos.'],


            // Vaso Governador (VG) - 28 pontos

            ['ponto' => 'VG1', 'descricao' => 'Vaso Governador 1 - Alivia dor nas costas e problemas genitais.'],
            ['ponto' => 'VG2', 'descricao' => 'Vaso Governador 2 - Alivia dor nas costas e problemas genitais.'],
            ['ponto' => 'VG3', 'descricao' => 'Vaso Governador 3 - Alivia dor nas costas e regula a menstruação.'],
            ['ponto' => 'VG4', 'descricao' => 'Vaso Governador 4 - Alivia dor nas costas e melhora a circulação sanguínea.'],
            ['ponto' => 'VG5', 'descricao' => 'Vaso Governador 5 - Alivia dor nas costas e distúrbios urinários.'],
            ['ponto' => 'VG6', 'descricao' => 'Vaso Governador 6 - Alivia dor nas costas e regula a digestão.'],
            ['ponto' => 'VG7', 'descricao' => 'Vaso Governador 7 - Alivia dor nas costas e problemas respiratórios.'],
            ['ponto' => 'VG8', 'descricao' => 'Vaso Governador 8 - Alivia dor nas costas e distúrbios menstruais.'],
            ['ponto' => 'VG9', 'descricao' => 'Vaso Governador 9 - Alivia dor nas costas e problemas digestivos.'],
            ['ponto' => 'VG10', 'descricao' => 'Vaso Governador 10 - Alivia dor nas costas e problemas digestivos.'],
            ['ponto' => 'VG11', 'descricao' => 'Vaso Governador 11 - Alivia dor nas costas e distúrbios menstruais.'],
            ['ponto' => 'VG12', 'descricao' => 'Vaso Governador 12 - Alivia dor nas costas e problemas respiratórios.'],
            ['ponto' => 'VG13', 'descricao' => 'Vaso Governador 13 - Alivia dor nas costas e melhora a circulação sanguínea.'],
            ['ponto' => 'VG14', 'descricao' => 'Vaso Governador 14 - Alivia dor nas costas e distúrbios urinários.'],
            ['ponto' => 'VG15', 'descricao' => 'Vaso Governador 15 - Alivia dor nas costas e problemas respiratórios.'],
            ['ponto' => 'VG16', 'descricao' => 'Vaso Governador 16 - Alivia dor nas costas e problemas digestivos.'],
            ['ponto' => 'VG17', 'descricao' => 'Vaso Governador 17 - Alivia dor nas costas e distúrbios menstruais.'],
            ['ponto' => 'VG18', 'descricao' => 'Vaso Governador 18 - Alivia dor nas costas e melhora a circulação sanguínea.'],
            ['ponto' => 'VG19', 'descricao' => 'Vaso Governador 19 - Alivia dor nas costas e problemas respiratórios.'],
            ['ponto' => 'VG20', 'descricao' => 'Vaso Governador 20 - Alivia dor nas costas e distúrbios urinários.'],
            ['ponto' => 'VG21', 'descricao' => 'Vaso Governador 21 - Alivia dor nas costas e problemas digestivos.'],
            ['ponto' => 'VG22', 'descricao' => 'Vaso Governador 22 - Alivia dor nas costas e problemas genitais.'],
            ['ponto' => 'VG23', 'descricao' => 'Vaso Governador 23 - Alivia dor nas costas e problemas digestivos.'],
            ['ponto' => 'VG24', 'descricao' => 'Vaso Governador 24 - Alivia dor nas costas e distúrbios menstruais.'],
            ['ponto' => 'VG25', 'descricao' => 'Vaso Governador 25 - Alivia dor nas costas e melhora a circulação sanguínea.'],
            ['ponto' => 'VG26', 'descricao' => 'Vaso Governador 26 - Alivia dor nas costas e problemas respiratórios.'],
            ['ponto' => 'VG27', 'descricao' => 'Vaso Governador 27 - Alivia dor nas costas e problemas digestivos.'],
            ['ponto' => 'VG28', 'descricao' => 'Vaso Governador 28 - Alivia dor nas costas e regula a menstruação.'],

        ];

        DB::table('sugestoes_pontos')->insert($pontos);

    }
}
